carsConfig = {
	ClassA = {
		{
			carBrand = 'Bravado',
			carModel = 'Banshee',
			carDescription = 'The Banshee is a recurring mid-sized sports car appearing in every GTA game since Grand Theft Auto III and shares its reputation with the Infernus for being one of the two longest running sports cars in the GTA series.',
			carTopSpeed = 180,
			carHorserPower = 473,
			carTraction = 4.2,
			image = 'banshee.png',
			price = 300,
		},
		{
			carBrand = 'Lampadati',
			carModel = 'furoregt',
			carDescription = 'From Los Santos to Nowhere, USA this updated classics looks, power, heritage and exclusivity will turn heads and open legs (opening legs not guaranteed). Its as conspicuous as consumption gets, and you dont care. Actually, you probably do care or you wouldnt be thinking about buying it.',
			carTopSpeed = 220,
			carHorserPower = 600,
			carTraction = 4.2,
			image = 'furoregt.png',
			price = 150,
		},
		{
			carBrand = 'Bravado',
			carModel = 'Banshee',
			carDescription = 'The Banshee is a recurring mid-sized sports car appearing in every GTA game since Grand Theft Auto III and shares its reputation with the Infernus for being one of the two longest running sports cars in the GTA series.',
			carTopSpeed = 180,
			carHorserPower = 473,
			carTraction = 4.2,
			image = 'banshee.png',
			price = 300,
		},
		{
			carBrand = 'Lampadati',
			carModel = 'furoregt',
			carDescription = 'From Los Santos to Nowhere, USA this updated classics looks, power, heritage and exclusivity will turn heads and open legs (opening legs not guaranteed). Its as conspicuous as consumption gets, and you dont care. Actually, you probably do care or you wouldnt be thinking about buying it.',
			carTopSpeed = 220,
			carHorserPower = 600,
			carTraction = 4.2,
			image = 'furoregt.png',
			price = 150,
		},
		{
			carBrand = 'Bravado',
			carModel = 'Banshee',
			carDescription = 'The Banshee is a recurring mid-sized sports car appearing in every GTA game since Grand Theft Auto III and shares its reputation with the Infernus for being one of the two longest running sports cars in the GTA series.',
			carTopSpeed = 180,
			carHorserPower = 473,
			carTraction = 4.2,
			image = 'banshee.png',
			price = 300,
		},
		{
			carBrand = 'Lampadati',
			carModel = 'furoregt',
			carDescription = 'From Los Santos to Nowhere, USA this updated classics looks, power, heritage and exclusivity will turn heads and open legs (opening legs not guaranteed). Its as conspicuous as consumption gets, and you dont care. Actually, you probably do care or you wouldnt be thinking about buying it.',
			carTopSpeed = 220,
			carHorserPower = 600,
			carTraction = 4.2,
			image = 'furoregt.png',
			price = 150,
		},
		{
			carBrand = 'Bravado',
			carModel = 'Banshee',
			carDescription = 'The Banshee is a recurring mid-sized sports car appearing in every GTA game since Grand Theft Auto III and shares its reputation with the Infernus for being one of the two longest running sports cars in the GTA series.',
			carTopSpeed = 180,
			carHorserPower = 473,
			carTraction = 4.2,
			image = 'banshee.png',
			price = 300,
		},
		{
			carBrand = 'Lampadati',
			carModel = 'furoregt',
			carDescription = 'From Los Santos to Nowhere, USA this updated classics looks, power, heritage and exclusivity will turn heads and open legs (opening legs not guaranteed). Its as conspicuous as consumption gets, and you dont care. Actually, you probably do care or you wouldnt be thinking about buying it.',
			carTopSpeed = 220,
			carHorserPower = 600,
			carTraction = 4.2,
			image = 'furoregt.png',
			price = 150,
		},
		{
			carBrand = 'Bravado',
			carModel = 'Banshee',
			carDescription = 'The Banshee is a recurring mid-sized sports car appearing in every GTA game since Grand Theft Auto III and shares its reputation with the Infernus for being one of the two longest running sports cars in the GTA series.',
			carTopSpeed = 180,
			carHorserPower = 473,
			carTraction = 4.2,
			image = 'banshee.png',
			price = 300,
		},
		{
			carBrand = 'Lampadati',
			carModel = 'furoregt',
			carDescription = 'From Los Santos to Nowhere, USA this updated classics looks, power, heritage and exclusivity will turn heads and open legs (opening legs not guaranteed). Its as conspicuous as consumption gets, and you dont care. Actually, you probably do care or you wouldnt be thinking about buying it.',
			carTopSpeed = 220,
			carHorserPower = 600,
			carTraction = 4.2,
			image = 'furoregt.png',
			price = 150,
		},
	},
	ClassB = {
		{
			carBrand = 'Dewbauchee',
			carModel = 'exemplar',
			carDescription = 'The Dewbauchee Exemplar is a four-door luxury coupé in Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'exemplar.png',
			price = 80,
		},
		{
			carBrand = 'Übermacht',
			carModel = 'SENTINEL',
			carDescription = 'The Sentinel is a recurring series of executive cars featured in both the 3D Universe and HD Universe, with the exception of Grand Theft Auto: Chinatown Wars. It is manufactured by Übermacht in the HD Universe.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'sentinel.png',
			price = 80,
		},
		{
			carBrand = 'Dewbauchee',
			carModel = 'exemplar',
			carDescription = 'The Dewbauchee Exemplar is a four-door luxury coupé in Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'exemplar.png',
			price = 80,
		},
		{
			carBrand = 'Übermacht',
			carModel = 'SENTINEL',
			carDescription = 'The Sentinel is a recurring series of executive cars featured in both the 3D Universe and HD Universe, with the exception of Grand Theft Auto: Chinatown Wars. It is manufactured by Übermacht in the HD Universe.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'sentinel.png',
			price = 80,
		},
		{
			carBrand = 'Dewbauchee',
			carModel = 'exemplar',
			carDescription = 'The Dewbauchee Exemplar is a four-door luxury coupé in Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'exemplar.png',
			price = 80,
		},
		{
			carBrand = 'Übermacht',
			carModel = 'SENTINEL',
			carDescription = 'The Sentinel is a recurring series of executive cars featured in both the 3D Universe and HD Universe, with the exception of Grand Theft Auto: Chinatown Wars. It is manufactured by Übermacht in the HD Universe.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'sentinel.png',
			price = 80,
		},
		{
			carBrand = 'Dewbauchee',
			carModel = 'exemplar',
			carDescription = 'The Dewbauchee Exemplar is a four-door luxury coupé in Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'exemplar.png',
			price = 80,
		},
		{
			carBrand = 'Übermacht',
			carModel = 'SENTINEL',
			carDescription = 'The Sentinel is a recurring series of executive cars featured in both the 3D Universe and HD Universe, with the exception of Grand Theft Auto: Chinatown Wars. It is manufactured by Übermacht in the HD Universe.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'sentinel.png',
			price = 80,
		},
	},
	ClassC = {
		{
			carBrand = 'Pegassi',
			carModel = 'faggio',
			carDescription = 'The Faggio (pronounced FAH•jee•oh) is a scooter that appeared in every game since Grand Theft Auto: Vice City except Grand Theft Auto Advance and Grand Theft Auto: Chinatown Wars. It is manufactured by Pegassi in the HD Universe.',
			carTopSpeed = 250,
			carHorserPower = 300,
			carTraction = 3.1,
			image = 'faggio.png',
			price = 80,
		},
		{
			carBrand = 'Bicycles',
			carModel = 'BMX',
			carDescription = 'The BMX is a bicycle in Grand Theft Auto: San Andreas, Grand Theft Auto: Vice City Stories, Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'bmx.png',
			price = 80,
		},
		{
			carBrand = 'Pegassi',
			carModel = 'faggio',
			carDescription = 'The Faggio (pronounced FAH•jee•oh) is a scooter that appeared in every game since Grand Theft Auto: Vice City except Grand Theft Auto Advance and Grand Theft Auto: Chinatown Wars. It is manufactured by Pegassi in the HD Universe.',
			carTopSpeed = 250,
			carHorserPower = 300,
			carTraction = 3.1,
			image = 'faggio.png',
			price = 80,
		},
		{
			carBrand = 'Bicycles',
			carModel = 'BMX',
			carDescription = 'The BMX is a bicycle in Grand Theft Auto: San Andreas, Grand Theft Auto: Vice City Stories, Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'bmx.png',
			price = 80,
		},
		{
			carBrand = 'Pegassi',
			carModel = 'faggio',
			carDescription = 'The Faggio (pronounced FAH•jee•oh) is a scooter that appeared in every game since Grand Theft Auto: Vice City except Grand Theft Auto Advance and Grand Theft Auto: Chinatown Wars. It is manufactured by Pegassi in the HD Universe.',
			carTopSpeed = 250,
			carHorserPower = 300,
			carTraction = 3.1,
			image = 'faggio.png',
			price = 80,
		},
		{
			carBrand = 'Bicycles',
			carModel = 'BMX',
			carDescription = 'The BMX is a bicycle in Grand Theft Auto: San Andreas, Grand Theft Auto: Vice City Stories, Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'bmx.png',
			price = 80,
		},
		{
			carBrand = 'Pegassi',
			carModel = 'faggio',
			carDescription = 'The Faggio (pronounced FAH•jee•oh) is a scooter that appeared in every game since Grand Theft Auto: Vice City except Grand Theft Auto Advance and Grand Theft Auto: Chinatown Wars. It is manufactured by Pegassi in the HD Universe.',
			carTopSpeed = 250,
			carHorserPower = 300,
			carTraction = 3.1,
			image = 'faggio.png',
			price = 80,
		},
		{
			carBrand = 'Bicycles',
			carModel = 'BMX',
			carDescription = 'The BMX is a bicycle in Grand Theft Auto: San Andreas, Grand Theft Auto: Vice City Stories, Grand Theft Auto V and Grand Theft Auto Online.',
			carTopSpeed = 120,
			carHorserPower = 80,
			carTraction = 3.1,
			image = 'bmx.png',
			price = 80,
		},
	}
}

